import {
  LayoutDashboard,
  BarChart3,
  Sun,
  CheckSquare,
  Target,
  Lightbulb,
  Flame,
  BookText,
  CalendarCheck,
  CalendarRange,
  Crosshair,
  Timer,
  GraduationCap,
  Dumbbell,
  Wallet,
  Library,
  Sparkles,
  Settings,
  Sunrise,
  Moon,
  Code,
  Flower2,
  Footprints,
  Droplets,
  BookOpen,
  Heart,
  Brain,
  Music,
  Palette,
  Coffee,
  Bike,
  type LucideIcon,
} from "lucide-react";

export const LIFEOS_ICON_MAP: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "bar-chart-3": BarChart3,
  sun: Sun,
  "check-square": CheckSquare,
  target: Target,
  lightbulb: Lightbulb,
  flame: Flame,
  "book-text": BookText,
  "calendar-check": CalendarCheck,
  "calendar-range": CalendarRange,
  crosshair: Crosshair,
  timer: Timer,
  "graduation-cap": GraduationCap,
  dumbbell: Dumbbell,
  wallet: Wallet,
  library: Library,
  sparkles: Sparkles,
  settings: Settings,
  sunrise: Sunrise,
  moon: Moon,
  code: Code,
  "flower-2": Flower2,
  footprints: Footprints,
  droplets: Droplets,
  "book-open": BookOpen,
  heart: Heart,
  brain: Brain,
  music: Music,
  palette: Palette,
  coffee: Coffee,
  bike: Bike,
};

export const HABIT_ICON_OPTIONS = [
  "dumbbell",
  "sunrise",
  "moon",
  "book-open",
  "code",
  "flower-2",
  "footprints",
  "droplets",
  "target",
  "heart",
  "brain",
  "music",
  "palette",
  "coffee",
  "bike",
  "flame",
];

export function LifeOsIcon({
  name,
  size = 20,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Cmp = LIFEOS_ICON_MAP[name] ?? Sparkles;
  return <Cmp size={size} className={className} />;
}
